# Generated by Django 5.1.6 on 2025-02-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('아우터', '아우터'), ('상의', '상의'), ('하의', '하의'), ('악세서리', '악세서리')], max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
